apiVersion: v1
kind: Service
metadata:
    name: app-nginx-service
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30000
    selector:
        app: app-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: app-nginx
    template:
        metadata:
            labels:
                app: app-nginx
                dude: "true"
        spec:
            containers:
                - name: nginx
                  image: 127.0.0.1:5000/test
                  ports:
                      - containerPort: 80
